/** 内部特徴量名 → 日本語ラベルの変換テーブル。Python 側の FEATURE_LABEL_JP と同期する。 */
export const SHAP_LABEL_JP: Record<string, string> = {
  weight_carried:              '斤量',
  horse_weight:                '馬体重',
  win_rate_all:                '通算勝率',
  win_rate_surface:            '馬場別勝率',
  win_rate_distance_band:      '距離帯別勝率',
  recent_rank_mean:            '直近5走平均着順',
  surface_code:                '馬場コード',
  sex_code:                    '性別コード',
  venue_encoded:               '開催場コード',
  sire_encoded:                '父馬コード',
  distance:                    '距離',
  horse_weight_diff:           '前走比体重差',
  gate_number:                 '枠番',
  condition_code:              '馬場状態',
  race_number:                 'レース番号',
  jockey_code_encoded:         '騎手コード',
  trainer_code_encoded:        '調教師コード',
  tc_4f:                       'ウッド4Fタイム',
  tc_lap:                      'ウッドラスト1Fタイム',
  tc_accel_flag:               'ウッド加速ラップ',
  tc_4f_diff:                  'ウッド前回比4F差',
  hc_4f:                       '坂路4Fタイム',
  hc_lap:                      '坂路ラスト1Fタイム',
  hc_accel_flag:               '坂路加速ラップ',
  hc_4f_diff:                  '坂路前回比4F差',
  win_rate_all_rank:           '通算勝率ランク',
  win_rate_all_zscore:         '通算勝率偏差値',
  win_rate_surface_rank:       '馬場別勝率ランク',
  win_rate_distance_band_rank: '距離帯別勝率ランク',
  recent_rank_mean_rank:       '直近着順ランク',
  recent_rank_mean_zscore:     '直近着順偏差値',
  tc_4f_rank:                  '調教タイムランク',
  tc_4f_zscore:                '調教タイム偏差値',
  today_inner_bias:            '当日内枠バイアス',
  today_front_bias:            '当日人気馬勝率',
  today_race_count:            '当日集計レース数',
  today_gate_match:            '当日枠バイアス相性',
  odds_vs_morning:             '朝一比オッズ変動',
  odds_velocity:               'オッズ下落速度',
  uf_win_rate_all:             'U:通算勝率スコア',
  uf_win_rate_surface:         'U:馬場別勝率スコア',
  uf_win_rate_distance:        'U:距離帯別勝率スコア',
  uf_recent_rank:              'U:直近着順スコア',
  uf_rank_trend:               'U:着順改善トレンド',
  uf_rest_days:                'U:休養日数スコア',
  uf_jockey_win_rate:          'U:騎手勝率スコア',
  uf_trainer_win_rate:         'U:調教師勝率スコア',
  uf_jockey_horse_combo:       'U:騎手×馬コンビスコア',
  uf_jockey_venue:             'U:騎手×会場スコア',
  uf_gate_fit:                 'U:枠番×馬場適性スコア',
  uf_venue_win_rate:           'U:会場勝率スコア',
  uf_east_west_match:          'U:厩舎東西一致スコア',
  uf_tc_speed:                 'U:ウッドスピード指数スコア',
  uf_hc_speed:                 'U:坂路スピード指数スコア',
  uf_sire_distance:            'U:父馬距離適性スコア',
  uf_bms_surface:              'U:母父馬場適性スコア',
  uf_father_sire:              'U:父の父スコア',
  uf_crowd_bias:               'U:大衆心理乖離スコア',
  u_score:                     'U合成スコア',
  days_since_last_race:        '前走からの日数',
  jockey_win_rate_90d:         '騎手直近90日勝率',
  trainer_win_rate_90d:        '調教師直近90日勝率',
  jockey_horse_combo_rate:     '騎手×馬コンビ勝率',
  jockey_venue_win_rate:       '騎手×会場勝率',
  venue_win_rate:              '当該会場勝率',
  tc_speed_index:              'ウッドスピード指数',
  hc_speed_index:              '坂路スピード指数',
  crowd_bias_ratio:            '大衆心理乖離率',
  x_consensus_score:           'X予想家コンセンサス',
}

export function shapLabel(featureName: string): string {
  return SHAP_LABEL_JP[featureName] ?? featureName
}
